### ISSUE TITLE
Very much needed, thanks!

### ISSUE THREAD

**Issue by kalanchoej** [wingleung/remix-aws#3]
Good work - the remix core assumption that we'd be using APIGatewayV2 is strange given the huge gap in functionality between that and V1/ALB.

**Comment by wingleung** [comment]
thanks! we're using it with ALB and APIGv1 because v1 has more features idd, especially for enterprise platforms.

From what I understand, the Remix guys want to focus on core feature of Remix and writing adapters for every cloud provider and its proxies is not part of the core responsibility.

fyi, https://github.com/remix-run/remix/pull/3173
